### ISSUE TITLE
Stripe Token is coming back undefined

### ISSUE THREAD

**Issue by FunkeDope** [tobyn/angular-stripe-checkout#23]
I'm not sure if I'm missing something obvious here, but after submitting a test payment using Checkout I'm getting an undefined `token` variable back in my controller. My HTML is as follows:
```html
<md-button 
    stripe-checkout="checkout()" 
    data-zip-code="true" 
    data-key="[test key]"
    data-name="Payment" 
    data-amount="{{plan.price*100}}">
        Upgrade Now!
</md-button>
```

And the Controller:
```javascript
function BillingCtrl($scope, StripeCheckout) {
    'use strict';
    $scope.checkout = function(token) {
        console.log('token:', token);
    };
}

angular.module('app').controller('BillingCtrl', BillingCtrl);
```

Any insight on what I may be missing?

**Comment by FunkeDope** [comment]
I figured it out. The `stripe-checkout` function has to be a string, not an actual function, so ``stripe-checkout="checkout()"`` is incorrect. The correct syntax is ``stripe-checkout="checkout"``. Might want to add this to the docs, I wasted way too much time on this!

**Comment by tobyn** [comment]
I'm glad you found the solution to your issue. Since someone else might wind up here with the same problem, let me clarify:

The argument passed to `stripe-checkout` should be an Angular expression that evaluates to the handler function you want to use. It "has to be a string" in the sense that *all* HTML attributes are ultimately strings, but that string can be an arbitrarily-complex expression.

In your case, `checkout` evaluates to the handler function you want to use, but `checkout()` *calls* that function with no arguments (which is why you were getting an `undefined` value for the token), and `angular-stripe-checkout` was receiving the return value of that function call (which was likely also `undefined`) as its handler function.

I can see how this would be confusing if you're not expecting it. Documentation is a bit lacking for this project in general, and I'll try to improve that in the future.
